openapi: 3.0.3
info:
  title: IoEngine RESTful API
  version: v0
servers:
  - url: /v0
paths:
  /upgrade:
    get:
      tags:
        - Upgrades
      operationId: get_upgrades
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/upgrades'
        '4XX':
          $ref: '#/components/responses/ClientError'
        '5XX':
          $ref: '#/components/responses/ServerError'
    put:
      tags:
        - Upgrades
      operationId: put_upgrades
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUpgradeBody'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/upgrades'
        '4XX':
          $ref: '#/components/responses/ClientError'
        '5XX':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    upgrades:
      description: Upgrade object, comprised of a spec and a state
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UpgradeID'
        spec:
          $ref: '#/components/schemas/UpgradeSpec'
        state:
          $ref: '#/components/schemas/UpgradeState'
      required:
        - id
        - spec
        - state
      minProperties: 1
    CreateUpgradeBody:
      example:
        namespace: 'mayastor'
        chartName: 'mayastor'
      description: Create Upgrade body JSON
      type: object
      properties:
        namespace:
          description: namespace where product is installed
          type: string
          items:
            example: 'mayastor'
            description: |-
              Product namespace
               Can be specified in the form of a string
               eg: "mayastor"
            type: string
        chartName:
          description: helm chart name used for product installation
          type: string
          items:
            example: 'mayastor'
            description: |-
              Helm chart name
               Can be specified in the form of a string
               eg: "mayastor"
            type: string
      required:
        - namespace
        - chartName
  responses:
    ClientError:
      description: Client side error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RestJsonError'
    ServerError:
      description: Server side error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RestJsonError'